<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan NBM Pemerintah - {{ config('app.name') }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 18px;
        }
        .header h2 {
            color: #666;
            margin: 5px 0 0 0;
            font-size: 14px;
            font-weight: normal;
        }
        .meta-info {
            background-color: #f8fafc;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .meta-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .meta-info td {
            padding: 3px 10px;
            font-size: 11px;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 6px 8px;
            text-align: left;
            font-size: 10px;
        }
        .data-table th {
            background-color: #f1f5f9;
            font-weight: bold;
            text-align: center;
        }
        .data-table td {
            text-align: center;
        }
        .data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
        .summary {
            background-color: #eff6ff;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
        .summary h3 {
            margin: 0 0 10px 0;
            color: #2563eb;
            font-size: 14px;
        }
        .summary-grid {
            display: table;
            width: 100%;
        }
        .summary-item {
            display: table-cell;
            width: 33.33%;
            text-align: center;
            padding: 5px;
        }
        .summary-value {
            font-size: 16px;
            font-weight: bold;
            color: #1e40af;
        }
        .summary-label {
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN NERACA BAHAN MAKANAN (NBM)</h1>
        <h2>Panel Pemerintah - Sistem Kolaborasi Ketahanan Pangan Nasional Indonesia</h2>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Filter Kelompok:</strong></td>
                <td>{{ $filters['kelompok'] ? 'Kelompok ' . $filters['kelompok'] : 'Semua Kelompok' }}</td>
                <td><strong>Generated By:</strong></td>
                <td>{{ $generated_by }}</td>
            </tr>
            <tr>
                <td><strong>Filter Tahun:</strong></td>
                <td>{{ $filters['tahun'] ?: 'Semua Tahun' }}</td>
                <td><strong>Generated At:</strong></td>
                <td>{{ $generated_at }}</td>
            </tr>
            <tr>
                <td><strong>Filter Bulan:</strong></td>
                <td>{{ $filters['bulan'] ? \Carbon\Carbon::create()->month($filters['bulan'])->translatedFormat('F') : 'Semua Bulan' }}</td>
                <td><strong>Total Records:</strong></td>
                <td>{{ $data->count() }} data (max 500)</td>
            </tr>
        </table>
    </div>

    @if($data->count() > 0)
        <div class="summary">
            <h3>Ringkasan Data</h3>
            <div class="summary-grid">
                <div class="summary-item">
                    <div class="summary-value">{{ $data->count() }}</div>
                    <div class="summary-label">Total Data</div>
                </div>
                <div class="summary-item">
                    <div class="summary-value">{{ number_format($data->avg('makanan'), 2) }}</div>
                    <div class="summary-label">Rata-rata Makanan (ribu ton)</div>
                </div>
                <div class="summary-item">
                    <div class="summary-value">{{ number_format($data->avg('kalori_hari'), 0) }}</div>
                    <div class="summary-label">Rata-rata Kalori/Hari</div>
                </div>
            </div>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th style="width: 4%;">No</th>
                    <th style="width: 6%;">Tahun</th>
                    <th style="width: 6%;">Bulan</th>
                    <th style="width: 20%;">Kelompok</th>
                    <th style="width: 24%;">Komoditi</th>
                    <th style="width: 10%;">Makanan (ribu ton)</th>
                    <th style="width: 10%;">Kalori/Hari</th>
                    <th style="width: 10%;">Harga Konsumen</th>
                    <th style="width: 10%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $item->tahun }}</td>
                    <td>{{ $item->bulan }}</td>
                    <td style="text-align: left;">{{ $item->kelompok ? $item->kelompok->nama : '-' }}</td>
                    <td style="text-align: left;">{{ $item->komoditi ? $item->komoditi->nama : '-' }}</td>
                    <td>{{ number_format($item->makanan ?? 0, 2) }}</td>
                    <td>{{ number_format($item->kalori_hari ?? 0, 2) }}</td>
                    <td>{{ number_format($item->harga_konsumen ?? 0, 0) }}</td>
                    <td>{{ ucfirst($item->status_angka ?? '-') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <h3>Tidak Ada Data</h3>
            <p>Tidak ditemukan data NBM dengan kriteria filter yang dipilih.</p>
        </div>
    @endif

    <div class="footer">
        <p><strong>{{ config('app.name') }}</strong> - Laporan ini dibuat secara otomatis pada {{ $generated_at }}</p>
        <p>Data ini hanya untuk keperluan internal instansi pemerintah dan tidak boleh disebarluaskan tanpa izin.</p>
    </div>
</body>
</html>
