<?php

namespace Database\Seeders;

use App\Models\DaftarAlamat;
use Illuminate\Database\Seeder;

class DaftarAlamatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alamatData = [
            [
                'provinsi' => 'Provinsi Aceh',
                'kabupaten_kota' => 'Kota Banda Aceh',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-perkebunan-banda-aceh.jpg',
                'nama_dinas' => 'Dinas Pertanian dan Perkebunan',
                'alamat' => 'Jl. T. Panglima Nyak Makam No.24, Kota Baru, Kec. Kuta Alam, Kota Banda Aceh, Aceh 24415',
                'telp' => '06517552342',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 5.5622,
                'longitude' => 95.3433,
            ],
            [
                'provinsi' => 'Provinsi Aceh',
                'kabupaten_kota' => 'Kabupaten Aceh Tengah',
                'gambar' => 'daftar-alamat/dinas-perkebunan-dan-kehutanan-aceh-tengah.jpeg',
                'nama_dinas' => 'Dinas Perkebunan dan Kehutanan',
                'alamat' => 'Jalan Kartini No.3, Bujang, Kec. Lut Tawar, Kabupaten Aceh Tengah, Aceh 24519',
                'telp' => '06437426361',
                'email' => 'disbunhut_acehtengah@yahoo.com',
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 4.6136,
                'longitude' => 96.8465,
            ],
            [
                'provinsi' => 'Provinsi Sumatera Utara',
                'kabupaten_kota' => 'Kota Medan',
                'gambar' => 'daftar-alamat/dinas-pertanian-tanaman-pangan-medan.jpg',
                'nama_dinas' => 'Dinas Pertanian Tanaman Pangan',
                'alamat' => 'Jl. Jenderal Besar A.H. Nasution No.6, Pangkalan Masyhur, Kec. Medan Johor, Kota Medan, Sumatera Utara 20219',
                'telp' => '0617860633',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 3.5424,
                'longitude' => 98.6777,
            ],
            [
                'provinsi' => 'Provinsi Sumatera Barat',
                'kabupaten_kota' => 'Kota Padang',
                'gambar' => 'daftar-alamat/dinas-pertanian-padang.jpeg',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Jl. Raya Sei Lareh, Lubuk Minturun, Kec. Koto Tangah, Kota Padang, Sumatera Barat 25586',
                'telp' => '0751495892',
                'email' => null,
                'website' => 'https://dispertanian.padang.go.id/',
                'status' => 'Aktif',
                'latitude' => -0.8588,
                'longitude' => 100.3996,
            ],
            [
                'provinsi' => 'Provinsi Riau',
                'kabupaten_kota' => 'Kabupaten Rokan Hulu',
                'gambar' => 'daftar-alamat/dinas-perikanan-dan-peternakan-rokan-hulu.png',
                'nama_dinas' => 'Dinas Perikanan dan Peternakan',
                'alamat' => 'Jl. Diponegoro KM.3, Koto Tinggi, Kec. Rambah, Kabupaten Rokan Hulu, Riau 28557',
                'telp' => '076291122',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 0.8485,
                'longitude' => 100.3203,
            ],
            [
                'provinsi' => 'Provinsi Kepulauan Riau',
                'kabupaten_kota' => 'Kota Batam',
                'gambar' => 'daftar-alamat/dinas-ketahanan-pangan-dan-pertanian-batam.png',
                'nama_dinas' => 'Dinas Ketahanan Pangan Dan Pertanian',
                'alamat' => 'Jl. Raja Ali H. No.3, sei harapan, Kec. Sekupang, Kota Batam, Kepulauan Riau 29444',
                'telp' => '081276513351',
                'email' => null,
                'website' => 'https://distankp.batam.go.id/',
                'status' => 'Aktif',
                'latitude' => 1.1093,
                'longitude' => 103.9530,
            ],
            [
                'provinsi' => 'Provinsi Jambi',
                'kabupaten_kota' => 'Kota Jambi',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-jambi.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Jl. Kapten Pattimura No.Km.10, Kenali Besar, Kec. Kota Baru, Kota Jambi, Jambi 36128',
                'telp' => '0741580573',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -1.6214,
                'longitude' => 103.5546,
            ],
            [
                'provinsi' => 'Provinsi Sumatera Selatan',
                'kabupaten_kota' => 'Kabupaten Musi Rawas',
                'gambar' => 'daftar-alamat/badan-ketahanan-pangan-musi-rawas.png',
                'nama_dinas' => 'Badan Ketahanan Pangan',
                'alamat' => 'Desa Muara Beliti Baru, Muara Beliti, Musi Rawas Regency, South Sumatra 31661',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -3.2481,
                'longitude' => 103.0115,
            ],
            [
                'provinsi' => 'Provinsi Bengkulu',
                'kabupaten_kota' => 'Kota Bengkulu',
                'gambar' => 'daftar-alamat/badan-pangan-dan-pertanian-bengkulu.png',
                'nama_dinas' => 'Badan Pangan dan Pertanian',
                'alamat' => 'Semarang, Sungai Serut, Bengkulu City, Bengkulu 38119',
                'telp' => '085273040022',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -3.7901,
                'longitude' => 102.3010,
            ],
            [
                'provinsi' => 'Provinsi Lampung',
                'kabupaten_kota' => 'Kota Bandar Lampung',
                'gambar' => 'daftar-alamat/dinas-ketahanan-pangan-tanaman-pangan-dan-hortikultura-bandar-lampung.png',
                'nama_dinas' => 'Dinas Ketahanan Pangan, Tanaman Pangan dan Hortikultura',
                'alamat' => 'JL. Hj Zainal Abidin Pagaralam No.01, Labuhan Ratu, Kec. Kedaton, Kota Bandar Lampung, Lampung 35132',
                'telp' => '0721704700',
                'email' => null,
                'website' => 'https://dinastph.lampungprov.go.id/',
                'status' => 'Aktif',
                'latitude' => -5.3628,
                'longitude' => 105.2258,
            ],
            [
                'provinsi' => 'Provinsi Kepulauan Bangka Belitung',
                'kabupaten_kota' => 'Kota Bangka',
                'gambar' => 'daftar-alamat/dinas-pangan-dan-pertanian-bangka.png',
                'nama_dinas' => 'Dinas Pangan dan Pertanian',
                'alamat' => 'Jl. Diponegoro No.10, Parit Padang, Sungai Liat, Kabupaten Bangka, Kepulauan Bangka Belitung 33215',
                'telp' => '071792300',
                'email' => null,
                'website' => 'http://dinpanpertan.bangka.go.id/',
                'status' => 'Aktif',
                'latitude' => -1.8849,
                'longitude' => 106.1023,
            ],
            [
                'provinsi' => 'Provinsi Banten',
                'kabupaten_kota' => 'Kota Serang',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-serang.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Kawasan Pusat Pemerintahan Provinsi Banten, Jl. Syech Nawawi Al-Bantani No.1, Curug, Sukajaya, Kec. Serang, Kota Serang, Banten 42171',
                'telp' => '0254267032',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -6.1707,
                'longitude' => 106.1598,
            ],
            [
                'provinsi' => 'Provinsi Daerah Khusus Jakarta',
                'kabupaten_kota' => 'Kota Jakarta Selatan',
                'gambar' => 'daftar-alamat/badan-ketahanan-pangan-kementerian-pertanian-jakarta-selatan.png',
                'nama_dinas' => 'Badan Ketahanan Pangan, Kementerian Pertanian',
                'alamat' => 'Gedung E Lantai IV, Jl. Harsono RM No.3 3, RT.5/RW.7, Ragunan, Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Jakarta 12550',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -6.2964,
                'longitude' => 106.8242,
            ],
            [
                'provinsi' => 'Provinsi Jawa Barat',
                'kabupaten_kota' => 'Kota Bandung',
                'gambar' => 'daftar-alamat/dinas-tanaman-pangan-dan-hortikultura-bandung.png',
                'nama_dinas' => 'Dinas Tanaman Pangan dan Hortikultura',
                'alamat' => 'Jl. Surapati No.71, Sadang Serang, Kecamatan Coblong, Kota Bandung, Jawa Barat 40133',
                'telp' => '0222503884',
                'email' => null,
                'website' => 'https://distanhorti.jabarprov.go.id/', 
                'status' => 'Aktif',
                'latitude' => -6.8989,
                'longitude' => 107.6228,
            ],
            [
                'provinsi' => 'Provinsi Jawa Tengah',
                'kabupaten_kota' => 'Kabupaten Semarang',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-perkebunan-semarang.png',
                'nama_dinas' => 'Dinas Pertanian dan Perkebunan',
                'alamat' => 'Komplek, Tarubudaya, Jl. Tarubudaya Jl. Jenderal Gatot Subroto, Bandarjo, Kec. Ungaran Bar., Kabupaten Semarang, Jawa Tengah 50517',
                'telp' => '0246921348',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -7.1105,
                'longitude' => 110.4147,
            ],
            [
                'provinsi' => 'Provinsi Daerah Istimewa Yogyakarta',
                'kabupaten_kota' => 'Kota Yogyakarta',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-pangan-yogyakarta.png',
                'nama_dinas' => 'Dinas Pertanian dan Pangan',
                'alamat' => 'Giwangan, Umbulharjo, Yogyakarta City, Special Region of Yogyakarta 55163',
                'telp' => '02744396955',
                'email' => null,
                'website' => 'https://pertanian.jogjakota.go.id/',
                'status' => 'Aktif',
                'latitude' => -7.8366,
                'longitude' => 110.3884,
            ],
            [
                'provinsi' => 'Provinsi Jawa Timur',
                'kabupaten_kota' => 'Kota Surabaya',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-surabaya.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Jl. Ahmad Yani No.152, Gayungan, Kec. Gayungan, Surabaya, Jawa Timur 60235',
                'telp' => '0318280110',
                'email' => null,
                'website' => 'http://pertanian.jatimprov.go.id/',
                'status' => 'Aktif',
                'latitude' => -7.3286,
                'longitude' => 112.7307,
            ],
            [
                'provinsi' => 'Provinsi Bali',
                'kabupaten_kota' => 'Kota Denpasar',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-denpasar.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Jl. WR Supratman No.71, Sumerta Kaja, Kec. Denpasar Tim., Kota Denpasar, Bali 80236',
                'telp' => '0361228716',
                'email' => null,
                'website' => 'http://distanpangan.baliprov.go.id/',
                'status' => 'Aktif',
                'latitude' => -8.6476,
                'longitude' => 115.2308,
            ],
            [
                'provinsi' => 'Provinsi Nusa Tenggara Barat',
                'kabupaten_kota' => 'Kabupaten Lombok Tengah',
                'gambar' => 'daftar-alamat/dinas-pertanian-lombok-tengah.png',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Ahmad Yani Street No.1, Praya, Central Lombok Regency, West Nusa Tenggara 83511',
                'telp' => '0370654015',
                'email' => null,
                'website' => 'http://pertanian.lomboktengahkab.go.id/',
                'status' => 'Aktif',
                'latitude' => -8.7053,
                'longitude' => 116.2707,
            ],
            [
                'provinsi' => 'Provinsi Nusa Tenggara Timur',
                'kabupaten_kota' => 'Kabupaten Sumba Timur',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-pangan-sumba-timur.png',
                'nama_dinas' => 'Dinas Pertanian dan Pangan',
                'alamat' => 'Jl. Gatot Soebroto No.8, Prailiu, Kec. Kambera, Kabupaten Sumba Timur, Nusa Tenggara Timur 87212',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -9.6573,
                'longitude' => 120.2793,
            ],
            [
                'provinsi' => 'Provinsi Kalimantan Barat',
                'kabupaten_kota' => 'Kota Pontianak',
                'gambar' => 'daftar-alamat/dinas-tanaman-pangan-dan-hortikultura-pontianak.png',
                'nama_dinas' => 'Dinas Tanaman Pangan dan Hortikultura',
                'alamat' => 'Jl. Alianyang No.17, Sungai Bangkong, Kec. Pontianak Kota, Kota Pontianak, Kalimantan Barat 78113',
                'telp' => '0561734017',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -0.0344,
                'longitude' => 109.3208,
            ],
            [
                'provinsi' => 'Provinsi Kalimantan Tengah',
                'kabupaten_kota' => 'Kota Palangka Raya',
                'gambar' => 'daftar-alamat/dinas-pertanian-palangkaraya.png',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Jl. Cilik Riwut No.Km. 7, RW.8, Bukit Tunggal, Kec. Jekan Raya, Kota Palangka Raya, Kalimantan Tengah 74874',
                'telp' => '05363232729',
                'email' => null,
                'website' => 'https://ketpang.palangkaraya.go.id/',
                'status' => 'Aktif',
                'latitude' => -2.2100,
                'longitude' => 113.9200,
            ],
            [
                'provinsi' => 'Provinsi Kalimantan Selatan',
                'kabupaten_kota' => 'Kabupaten Banjar',
                'gambar' => 'daftar-alamat/dinas-tanaman-pangan-dan-hortikultura-banjar.png',
                'nama_dinas' => 'Dinas Tanaman Pangan dan Hortikultura',
                'alamat' => 'Jl. Keramat, Cindai Alus, Kec. Martapura, Kabupaten Banjar, Kalimantan Selatan 70612',
                'telp' => null,
                'email' => null,
                'website' => 'https://pertanian.banjarkab.go.id/',
                'status' => 'Aktif',
                'latitude' => -3.4029,
                'longitude' => 114.8149,
            ],
            [
                'provinsi' => 'Provinsi Kalimantan Timur',
                'kabupaten_kota' => 'Kota Samarinda',
                'gambar' => 'daftar-alamat/dinas-ketahanan-pangan-dan-pertanian-samarinda.png',
                'nama_dinas' => 'Dinas Ketahanan Pangan dan Pertanian',
                'alamat' => 'Jl. Biola No.1, Sungai Pinang Luar, Kec. Samarinda Kota, Kota Samarinda, Kalimantan Timur 75117',
                'telp' => null,
                'email' => null,
                'website' => 'https://distapangtani.samarindakota.go.id/',
                'status' => 'Aktif',
                'latitude' => -0.4893,
                'longitude' => 117.1485,
            ],
            [
                'provinsi' => 'Provinsi Kalimantan Utara',
                'kabupaten_kota' => 'Kabupaten Nunukan',
                'gambar' => 'daftar-alamat/dinas-ketahanan-pangan-dan-pertanian-nunukan.png',
                'nama_dinas' => 'Dinas Ketahanan Pangan dan Pertanian',
                'alamat' => 'Kompleks Perkantoran Gabungan Dinas (Gadis I), Jl. Ujang Dewa, Sedadap, Prov., Nunukan Sel., Kabupaten Nunukan, Kalimantan Utara 77482',
                'telp' => '055622843',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 3.0731,
                'longitude' => 116.0414,
            ],
            [
                'provinsi' => 'Provinsi Sulawesi Utara',
                'kabupaten_kota' => 'Kabupaten Minahasa',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-peternakan-minahasa.png',
                'nama_dinas' => 'Dinas Pertanian dan Peternakan',
                'alamat' => 'Kalasey Satu, Pineleng, Minahasa Regency, North Sulawesi',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => 1.4555,
                'longitude' => 124.7643,
            ],
            [
                'provinsi' => 'Provinsi Sulawesi Tengah',
                'kabupaten_kota' => 'Kabupaten Sigi',
                'gambar' => 'daftar-alamat/balai-pengkajian-teknologi-pertanian-sigi.png',
                'nama_dinas' => 'Balai Pengkajian Teknologi Pertanian',
                'alamat' => 'Jl. Poros Palu - Kulawi No.KM 17, Maku, Kec. Dolo, Kabupaten Sigi, Sulawesi Tengah 94362',
                'telp' => '04514013202',
                'email' => null,
                'website' => 'http://sulteng.bsip.pertanian.go.id/',
                'status' => 'Aktif',
                'latitude' => -1.0351,
                'longitude' => 119.8875,
            ],
            [
                'provinsi' => 'Provinsi Sulawesi Selatan',
                'kabupaten_kota' => 'Kota Makassar',
                'gambar' => 'daftar-alamat/dinas-pertanian-peternakan-ketahanan-pangan-makassar.png',
                'nama_dinas' => 'Dinas Pertanian, Peternakan & Ketahanan Pangan',
                'alamat' => 'Jl. Bandang No.30, Bontoala Tua, Kec. Bontoala, Kota Makassar, Sulawesi Selatan 90154',
                'telp' => '041421208',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -5.1271,
                'longitude' => 119.4191,
            ],
            [
                'provinsi' => 'Provinsi Sulawesi Tenggara',
                'kabupaten_kota' => 'Kota Kendari',
                'gambar' => 'daftar-alamat/dinas-pertanian-kota-kendari.png',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Jl. Balai Kota, Mandonga, Kec. Mandonga, Kota Kendari, Sulawesi Tenggara 93111',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -3.9721,
                'longitude' => 122.5100,
            ],
            [
                'provinsi' => 'Provinsi Gorontalo',
                'kabupaten_kota' => 'Kabupaten Gorontalo',
                'gambar' => 'daftar-alamat/dinas-pertanian-tanaman-pangan-dan-hortikultura-gorontalo.png',
                'nama_dinas' => 'Dinas Pertanian Tanaman Pangan Dan Hortikultura',
                'alamat' => 'Tinelo Ayula, Bulango Selatan, Gorontalo Regency, Gorontalo 96125',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -0.5992,
                'longitude' => 123.0724,
            ],
            [
                'provinsi' => 'Provinsi Sulawesi Barat',
                'kabupaten_kota' => 'Kabupaten Polewali Mandar',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-peternakan-polewali-mandar.png',
                'nama_dinas' => 'Dinas Pertanian dan Peternakan',
                'alamat' => 'JL. Muhamad Yamin No.177, Madatte, Kec. Polewali, Kabupaten Polewali Mandar, Sulawesi Barat 91311',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -3.4081,
                'longitude' => 119.3052,
            ],
            [
                'provinsi' => 'Provinsi Maluku',
                'kabupaten_kota' => 'Kota Ambon',
                'gambar' => 'daftar-alamat/dinas-pertanian-ambon.png',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Jl. W.R. Supratman No.21, Uritetu, Kec. Sirimau, Kota Ambon, Maluku 97124',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -3.6924,
                'longitude' => 128.1847,
            ],
            [
                'provinsi' => 'Provinsi Maluku Utara',
                'kabupaten_kota' => 'Kota Tidore Kepulauan',
                'gambar' => 'daftar-alamat/dinas-pertanian-tidore-kepulauan.png',
                'nama_dinas' => 'Dinas Pertanian',
                'alamat' => 'Komp. Pertanian, Jl. Raya Kusu, Sofifi, Galala, Tidore, Kota Tidore Kepulauan, Maluku Utara',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -0.6957,
                'longitude' => 127.5557,
            ],
            [
                'provinsi' => 'Provinsi Papua Barat',
                'kabupaten_kota' => 'Kabupaten Manokwari',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-manokwari.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Jl. Percetakan Sanggeng, Sanggeng, Kec. Manokwari Bar., Kabupaten Manokwari, Papua Bar. 98312',
                'telp' => '0986211961',
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -2.6729,
                'longitude' => 138.0445,
            ],
            [
                'provinsi' => 'Provinsi Papua',
                'kabupaten_kota' => 'Kota Jayapura',
                'gambar' => 'daftar-alamat/dinas-pertanian-dan-ketahanan-pangan-jayapura.png',
                'nama_dinas' => 'Dinas Pertanian dan Ketahanan Pangan',
                'alamat' => 'Wahno, Abepura, Jayapura City, Papua',
                'telp' => null,
                'email' => null,
                'website' => null,
                'status' => 'Aktif',
                'latitude' => -2.5955,
                'longitude' => 140.6818,
            ],
        ];

        foreach ($alamatData as $data) {
            DaftarAlamat::create($data);
        }
    }
}
