<?php
/**
 * TOP 30 RECOMMENDED COMMODITIES FOR LSTM TRAINING
 * Generated by analyze_sql_quality.php on 2026-01-17 01:59:18
 * 
 * Estimated sequences: 12,816
 * Quality threshold: EXCELLENT or GOOD
 */

return [
    'alpokat' => ['05', '0501', 'transaksi_nbms_alpokat_app3.sql'],
    'apel' => ['05', '0522', 'transaksi_nbms_apel_app3.sql'],
    'bawangmerah' => ['06', '0601', 'transaksi_nbms_bawangmerah_app3.sql'],
    'bawangputih' => ['06', '0618', 'transaksi_nbms_bawangputih_app3.sql'],
    'bayam' => ['06', '0617', 'transaksi_nbms_bayam_app3.sql'],
    'belimbing' => ['05', '0515', 'transaksi_nbms_belimbing_app3.sql'],
    'beras' => ['01', '0102', 'transaksi_nbms_beras_app3.sql'],
    'beras_enhanced_test' => ['01', '0102', 'transaksi_nbms_beras_enhanced_test_app3.sql'],
    'buncis' => ['06', '0616', 'transaksi_nbms_buncis_app3.sql'],
    'cabai' => ['06', '0609', 'transaksi_nbms_cabai_app3.sql'],
    'dagingayamburas' => ['07', '0707', 'transaksi_nbms_dagingayamburas_app3.sql'],
    'dagingayamras' => ['07', '0708', 'transaksi_nbms_dagingayamras_app3.sql'],
    'dagingbabi' => ['07', '0706', 'transaksi_nbms_dagingbabi_app3.sql'],
    'dagingbebek' => ['07', '0709', 'transaksi_nbms_dagingbebek_app3.sql'],
    'dagingdomba' => ['07', '0704', 'transaksi_nbms_dagingdomba_app3.sql'],
    'dagingkambing' => ['07', '0703', 'transaksi_nbms_dagingkambing_app3.sql'],
    'dagingkuda' => ['07', '0705', 'transaksi_nbms_dagingkuda_app3.sql'],
    'dagingsapi' => ['07', '0701', 'transaksi_nbms_dagingsapi_app3.sql'],
    'daunbawang' => ['06', '0612', 'transaksi_nbms_daunbawang_app3.sql'],
    'duku' => ['05', '0503', 'transaksi_nbms_duku_app3.sql'],
    'durian' => ['05', '0504', 'transaksi_nbms_durian_app3.sql'],
    'gulamangkok' => ['03', '0302', 'transaksi_nbms_gulamangkok_app3.sql'],
    'gulapasir' => ['03', '0301', 'transaksi_nbms_gulapasir_app3.sql'],
    'jagung' => ['01', '0103', 'transaksi_nbms_jagung_app3.sql'],
    'jagungbasah' => ['01', '0104', 'transaksi_nbms_jagungbasah_app3.sql'],
    'jambu' => ['05', '0505', 'transaksi_nbms_jambu_app3.sql'],
    'jambuair' => ['05', '0523', 'transaksi_nbms_jambuair_app3.sql'],
    'jamur' => ['06', '0620', 'transaksi_nbms_jamur_app3.sql'],
    'jengkol' => ['06', '0624', 'transaksi_nbms_jengkol_app3.sql'],
    'jeroan' => ['07', '0710', 'transaksi_nbms_jeroan_app3.sql'],
];
